# Generated by Django 3.0.5 on 2021-01-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('white', 'Biały'), ('blue', 'Niebieski'), ('yellow', 'Żółty'), ('pink', 'Różowy'), ('green', 'Zielony'), ('brown', 'Brązowy'), ('purple', 'Fioletowy'), ('multicolour', 'Wielokolorowy'), ('gold', 'Złoty'), ('silver', 'Srebrny')], max_length=255)),
                ('ready_in', models.CharField(choices=[('now', '1-3 dni'), ('week', 'do 7 dni'), ('month', 'do 30 dni')], max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
