# Generated by Django 3.0.5 on 2020-09-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('Żółty', 'Żółty'), ('Czerwony', 'Czerwony'), ('Biały', 'Biały'), ('Zielony', 'Zielony'), ('Różowy', 'Różowy'), ('Fioletowy', 'Fioletowy'), ('Niebieski', 'Niebieski'), ('Czarny', 'Czarny'), ('Brązowy', 'Brązowy')], max_length=255)),
                ('ready_in', models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni'), ('do 7 dni', 'do 7 dni')], max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
