# Generated by Django 2.2.10 on 2020-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Decorations', 'Decorations'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Other', 'Other')], default='Other', max_length=255)),
            ],
        ),
    ]
