# Generated by Django 3.0.5 on 2020-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Niebieski', 'Niebieski'), ('Czarny', 'Czarny'), ('Zielony', 'Zielony'), ('Brązowy', 'Brązowy'), ('Czerwony', 'Czerwony'), ('Różowy', 'Różowy'), ('Fioletowy', 'Fioletowy'), ('Żółty', 'Żółty'), ('Biały', 'Biały')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 30 dni', 'do 30 dni'), ('1-3 dni', '1-3 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
