# Generated by Django 3.0.5 on 2020-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200928_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('red', 'Czerwony'), ('black', 'Czarny'), ('white', 'Biały'), ('blue', 'Niebieski'), ('yellow', 'Żółty'), ('pink', 'Różowy'), ('green', 'Zielony'), ('brown', 'Brązowy'), ('purple', 'Fioletowy'), ('multicolour', 'Wielokolorowy'), ('gold', 'Złoty'), ('silver', 'Srebrny')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('now', '1-3 dni'), ('week', 'do 7 dni'), ('month', 'do 30 dni')], max_length=255),
        ),
    ]
