# Generated by Django 3.0.5 on 2020-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Brązowy', 'Brązowy'), ('Niebieski', 'Niebieski'), ('Różowy', ' Różowy'), ('Czarny', 'Czarny'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony'), ('Fioletowy', 'Fioletowy'), ('Żółty', 'Żółty')], max_length=255),
        ),
    ]
