# Generated by Django 3.0.5 on 2020-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200420_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Różowy', ' Różowy'), ('Zielony', 'Zielony'), ('Czarny', 'Czarny'), ('Fioletowy', 'Fioletowy'), ('Czerwony', 'Czerwony'), ('Biały', 'Biały'), ('Niebieski', 'Niebieski'), ('Żółty', 'Żółty'), ('Brązowy', 'Brązowy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 7 dni', 'do 7 dni'), ('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni')], max_length=255),
        ),
    ]
