# Generated by Django 3.0.5 on 2020-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200420_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Zielony', 'Zielony'), ('Fioletowy', 'Fioletowy'), ('Brązowy', 'Brązowy'), ('Niebieski', 'Niebieski'), ('Czarny', 'Czarny'), ('Żółty', 'Żółty'), ('Różowy', ' Różowy'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
