# Generated by Django 3.0.5 on 2020-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200421_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Różowy', ' Różowy'), ('Fioletowy', 'Fioletowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony'), ('Żółty', 'Żółty'), ('Niebieski', 'Niebieski'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały')], max_length=255),
        ),
    ]
