# Generated by Django 3.0.5 on 2020-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200421_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Różowy', ' Różowy'), ('Niebieski', 'Niebieski'), ('Żółty', 'Żółty'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały'), ('Fioletowy', 'Fioletowy'), ('Czarny', 'Czarny')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 7 dni', 'do 7 dni'), ('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni')], max_length=255),
        ),
    ]
