# Generated by Django 3.0.5 on 2020-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20200421_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Brązowy', 'Brązowy'), ('Żółty', 'Żółty'), ('Czarny', 'Czarny'), ('Fioletowy', 'Fioletowy'), ('Różowy', ' Różowy'), ('Niebieski', 'Niebieski'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 7 dni', 'do 7 dni'), ('do 30 dni', 'do 30 dni'), ('1-3 dni', '1-3 dni')], max_length=255),
        ),
    ]
