# Generated by Django 3.0.5 on 2020-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20200421_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Niebieski', 'Niebieski'), ('Żółty', 'Żółty'), ('Zielony', 'Zielony'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały'), ('Fioletowy', 'Fioletowy'), ('Czarny', 'Czarny'), ('Różowy', ' Różowy'), ('Czerwony', 'Czerwony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 7 dni', 'do 7 dni'), ('do 30 dni', 'do 30 dni')], max_length=255),
        ),
    ]
