# Generated by Django 3.0.5 on 2020-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_auto_20200421_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Zielony', 'Zielony'), ('Czerwony', 'Czerwony'), ('Fioletowy', 'Fioletowy'), ('Biały', 'Biały'), ('Żółty', 'Żółty'), ('Różowy', ' Różowy'), ('Czarny', 'Czarny'), ('Brązowy', 'Brązowy'), ('Niebieski', 'Niebieski')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 30 dni', 'do 30 dni'), ('1-3 dni', '1-3 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
