# Generated by Django 3.0.5 on 2020-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20200427_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Żółty', 'Żółty'), ('Biały', 'Biały'), ('Niebieski', 'Niebieski'), ('Zielony', 'Zielony'), ('Różowy', ' Różowy'), ('Czarny', 'Czarny'), ('Brązowy', 'Brązowy'), ('Czerwony', 'Czerwony'), ('Fioletowy', 'Fioletowy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
