# Generated by Django 3.0.5 on 2020-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20200514_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Żółty', 'Żółty'), ('Czarny', 'Czarny'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały'), ('Zielony', 'Zielony'), ('Różowy', ' Różowy'), ('Fioletowy', 'Fioletowy'), ('Niebieski', 'Niebieski'), ('Czerwony', 'Czerwony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 30 dni', 'do 30 dni'), ('1-3 dni', '1-3 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
