# Generated by Django 3.0.5 on 2020-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_auto_20200514_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Niebieski', 'Niebieski'), ('Żółty', 'Żółty'), ('Czarny', 'Czarny'), ('Zielony', 'Zielony'), ('Brązowy', 'Brązowy'), ('Fioletowy', 'Fioletowy'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Różowy', ' Różowy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 7 dni', 'do 7 dni'), ('do 30 dni', 'do 30 dni')], max_length=255),
        ),
    ]
