# Generated by Django 3.0.5 on 2020-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20200521_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Żółty', 'Żółty'), ('Brązowy', 'Brązowy'), ('Fioletowy', 'Fioletowy'), ('Zielony', 'Zielony'), ('Niebieski', 'Niebieski'), ('Różowy', ' Różowy'), ('Czarny', 'Czarny')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 30 dni', 'do 30 dni'), ('do 7 dni', 'do 7 dni'), ('1-3 dni', '1-3 dni')], max_length=255),
        ),
    ]
