# Generated by Django 3.0.5 on 2020-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_auto_20200525_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Żółty', 'Żółty'), ('Biały', 'Biały'), ('Różowy', 'Różowy'), ('Brązowy', 'Brązowy'), ('Czerwony', 'Czerwony'), ('Zielony', 'Zielony'), ('Fioletowy', 'Fioletowy'), ('Niebieski', 'Niebieski')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('2', 'do 7 dni'), ('1', '1-3 dni'), ('3', 'do 30 dni')], max_length=255),
        ),
    ]
