# Generated by Django 3.0.5 on 2020-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_auto_20200603_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Brązowy', 'Brązowy'), ('Fioletowy', 'Fioletowy'), ('Żółty', 'Żółty'), ('Czerwony', 'Czerwony'), ('Biały', 'Biały'), ('Różowy', 'Różowy'), ('Zielony', 'Zielony'), ('Czarny', 'Czarny'), ('Niebieski', 'Niebieski')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('do 7 dni', 'do 7 dni'), ('do 30 dni', 'do 30 dni'), ('1-3 dni', '1-3 dni')], max_length=255),
        ),
    ]
