# Generated by Django 3.0.5 on 2020-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0033_auto_20200603_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Biały', 'Biały'), ('Czarny', 'Czarny'), ('Czerwony', 'Czerwony'), ('Niebieski', 'Niebieski'), ('Zielony', 'Zielony'), ('Brązowy', 'Brązowy'), ('Fioletowy', 'Fioletowy'), ('Różowy', 'Różowy'), ('Żółty', 'Żółty')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ready_in',
            field=models.CharField(choices=[('1-3 dni', '1-3 dni'), ('do 30 dni', 'do 30 dni'), ('do 7 dni', 'do 7 dni')], max_length=255),
        ),
    ]
