# Generated by Django 3.0.5 on 2021-03-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
        ('category', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='post_gallery', to='upload_image.Image'),
        ),
    ]
