# Generated by Django 3.0.5 on 2020-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=0, max_length=550),
            preserve_default=False,
        ),
    ]
