# Generated by Django 3.0.5 on 2021-01-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_image', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=1000)),
                ('gender', models.CharField(choices=[('woman', 'Damski'), ('man', 'Męski'), ('dziecięcy', 'Dziecięcy'), ('uniwersalny', 'Uniwersalny')], default='Wszyscy', max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('shipping_abroad', models.CharField(choices=[('true', 'Tak'), ('false', 'Nie')], max_length=5)),
                ('gallery', models.ManyToManyField(blank=True, null=True, related_name='gallery', to='upload_image.Image')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
