# Generated by Django 3.0.5 on 2020-09-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=1000)),
                ('gender', models.CharField(choices=[('Damski', 'Damski'), ('Męski', 'Męski'), ('Dziecięcy', 'Dziecięcy'), ('Uniwersalny', 'Uniwersalny')], default='Wszyscy', max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('shipping_abroad', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=1)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
