# Generated by Django 3.0.5 on 2020-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
