# Generated by Django 3.0.5 on 2021-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery', to='upload_image.Image'),
        ),
    ]
