# Generated by Django 2.2.10 on 2020-02-18 13:51

from django.db import migrations, models
import offer.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=offer.models.upload_location),
        ),
    ]
