# Generated by Django 3.0.5 on 2020-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='amount',
        ),
        migrations.AlterField(
            model_name='offer',
            name='gender',
            field=models.CharField(choices=[('woman', 'Damski'), ('man', 'Męski'), ('dziecięcy', 'Dziecięcy'), ('uniwersalny', 'Uniwersalny')], default='Wszyscy', max_length=255),
        ),
    ]
