# Generated by Django 3.0.5 on 2020-04-02 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0002_offer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='likes',
        ),
        migrations.AddField(
            model_name='offer',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
