# Generated by Django 3.0.5 on 2020-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
