# Generated by Django 3.0.5 on 2021-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20210330_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
