# Generated by Django 3.0.5 on 2020-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200928_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shipping_abroad',
            field=models.CharField(choices=[('true', 'Tak'), ('false', 'Nie')], max_length=5),
        ),
    ]
