# Generated by Django 3.0.5 on 2021-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shipping_abroad',
            field=models.BooleanField(default=False),
        ),
    ]
