# Generated by Django 3.0.5 on 2020-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
