# Generated by Django 3.0.5 on 2020-04-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200402_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='liked_by',
        ),
    ]
