# Generated by Django 3.0.5 on 2020-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='amount',
        ),
    ]
