# Generated by Django 3.0.5 on 2020-06-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
