# Generated by Django 3.0.5 on 2020-04-21 16:20

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/default_image.jpeg', upload_to=user.models.upload_location),
        ),
    ]
