# Generated by Django 3.0.5 on 2020-04-21 16:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200421_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=user.models.upload_location),
        ),
    ]
